Vagrant.configure("2") do |config|
    config.vm.box = "geerlingguy/centos8"
  
    config.ssh.insert_key = false
    config.vm.synced_folder ".", "/vagrant", disabled: true
  
    config.vm.provider :virtualbox do |v|
      v.memory = 512 
      v.linked_clone = true
    end
    
    # Consul node-1 
    config.vm.define "consul-node1" do |consul|
      consul.vm.hostname = "consul-node1"
      consul.vm.network :private_network, ip: "192.168.60.2"
    end
  
    # Consul node-2 
    config.vm.define "consul-node2" do |consul|
      consul.vm.hostname = "consul-node2"
      consul.vm.network :private_network, ip: "192.168.60.3"
    end
  
    # Consul node-3 
    config.vm.define "consul-node3" do |consul|
      consul.vm.hostname = "consul-node3"
      consul.vm.network :private_network, ip: "192.168.60.4"
    end
  
    # PostgreSQL + Patroni server-1 
    config.vm.define "pg-patroni1" do |patroni|
      patroni.vm.hostname = "pg-patroni1"
      patroni.vm.network :private_network, ip: "192.168.60.11"
    end
  
    # PostgreSQL + Patroni server-2 
    config.vm.define "pg-patroni2" do |patroni|
      patroni.vm.hostname = "pg-patroni2"
      patroni.vm.network :private_network, ip: "192.168.60.12"
    end 
  
    # PostgreSQL + Patroni server-3 
    config.vm.define "pg-patroni3" do |patroni|
      patroni.vm.hostname = "pg-patroni3"
      patroni.vm.network :private_network, ip: "192.168.60.13"
    end
  
    # Pgbouncer node 
    config.vm.define "pgbouncer" do |pgbouncer|
      pgbouncer.vm.hostname = "pgbouncer"
      pgbouncer.vm.network :private_network, ip: "192.168.60.14"
    end
  end 